import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { gzipSync } from 'node:zlib';
import { buildRates, buildPlayers, chooseCurrent, impliedPoints, prepareData, rushPlay, targetPlay, number, zoneFor } from '../lib/model.mjs';
import { Provider, DATASETS, datasetUrl } from '../lib/providers.mjs';
import { validateQuery, SourceStore } from '../lib/source.mjs';
const play=(changes={})=>({game_id:'2025_18_A_B',season:'2025',week:'18',play_id:'1',play_type:'run',posteam:'A',defteam:'B',rush_attempt:'1',rusher_player_id:'p1',rush_touchdown:'0',rushing_yards:'4',yardline_100:'3',...changes});
const rates=buildRates([play(),play({rush_touchdown:'1',rushing_yards:'3'}),play({rush_attempt:'0',pass_attempt:'1',receiver_player_id:'p1',passer_player_id:'q1',complete_pass:'1',passing_yards:'3',air_yards:'3',pass_touchdown:'1'}),play({yardline_100:'50'})]);
function fixture(){
 const schedule=[{game_id:'2025_18_A_B',season:'2025',week:'18',gameday:'2026-01-01',game_type:'REG',home_team:'B',away_team:'A'},{game_id:'2026_01_A_B',season:'2026',week:'1',gameday:'2026-09-10',game_type:'REG',home_team:'B',away_team:'A'},{game_id:'2026_02_B_A',season:'2026',week:'2',gameday:'2026-09-17',game_type:'REG',home_team:'A',away_team:'B',spread_line:'3',total_line:'45'},{game_id:'2026_03_A_B',season:'2026',week:'3',gameday:'2026-09-24',game_type:'REG',home_team:'B',away_team:'A'}];
 const roster={gsis_id:'p1',pfr_id:'pfr1',full_name:'Sample Runner',position:'RB',team:'A',season:'2026',week:'2',status:'ACT'};
 const weekly=[{player_id:'p1',team:'A',position:'RB',carries:'10',rushing_yards:'40',rushing_tds:'0',receptions:'2',targets:'3',receiving_tds:'0',game_id:schedule[0].game_id},{player_id:'p1',team:'A',position:'RB',carries:'20',rushing_yards:'100',rushing_tds:'1',receptions:'4',targets:'5',receiving_tds:'0',game_id:schedule[1].game_id},{player_id:'p1',team:'A',position:'RB',carries:'90',rushing_yards:'999',rushing_tds:'10',game_id:schedule[2].game_id}];
 const pbp=schedule.slice(0,3).flatMap((g,i)=>[play({game_id:g.game_id,season:g.season,week:g.week,play_id:'1'}),play({game_id:g.game_id,season:g.season,week:g.week,desc:'END GAME',rush_attempt:'0',rusher_player_id:''})]);
 return {schedule,roster,weekly,pbp};
}
function boardFixture(changes={}){const f=fixture(),rosters=changes.rosters||[f.roster];return buildPlayers({games:prepareData({schedule:f.schedule,pbp:changes.pbp||f.pbp,weekly:changes.weekly||f.weekly,rosters,snaps:changes.snaps||[],chart:changes.chart||[]}),rosters,season:2026,week:2,market:'any_td',rates,trainingSeason:2025,...changes});}
test('zero and missing values stay distinct',()=>{assert.equal(number(''),null);assert.equal(number('0'),0);assert.equal(number('NaN'),null);assert.equal(zoneFor(null),null);});
test('field zones include their correct boundaries',()=>{assert.deepEqual([1,5,6,20,21,40,41,99].map(zoneFor),['goal_line','goal_line','red_zone','red_zone','fringe','fringe','open','open']);});
test('nullified plays, two point tries and kneels do not generate modeled carries',()=>{for(const flags of [{play_type:'no_play'},{two_point_attempt:'1'},{play_deleted:'1'},{qb_kneel:'1'}])assert.equal(rushPlay(play(flags)),false);assert.equal(rushPlay(play({rushing_yards:'-2'})),true);});
test('sacks, spikes and unassigned throwaways are not targets',()=>{const p=play({rush_attempt:'0',pass_attempt:'1',receiver_player_id:'r'});assert.equal(targetPlay(p),true);for(const f of [{sack:'1'},{qb_spike:'1'},{receiver_player_id:''}])assert.equal(targetPlay({...p,...f}),false);});
test('conversion rates are estimated from counts, separately by play type',()=>{assert.equal(rates.zones['rush:goal_line'].rate,.5);assert.equal(rates.zones['pass:goal_line'].rate,1);assert.equal(rates.zones['rush:open'].rate,0);});
test('schedule spread sign gives correct home and away implied totals',()=>{const g={home_team:'A',total_line:'46',spread_line:'6'};assert.deepEqual(impliedPoints(g,'A'),{points_favored:6,implied_total:26});assert.deepEqual(impliedPoints(g,'B'),{points_favored:-6,implied_total:20});assert.equal(impliedPoints({...g,total_line:''},'A').implied_total,null);});
test('automatic week remains through Monday and advances Tuesday',()=>{const {schedule}=fixture();assert.deepEqual(chooseCurrent(schedule,new Date('2026-09-20T22:00:00Z')),{season:2026,week:2});assert.equal(chooseCurrent(schedule,new Date('2026-09-21T12:00:00Z')).week,2);assert.equal(chooseCurrent(schedule,new Date('2026-09-22T12:00:00Z')).week,3);});
test('January belongs to the prior NFL season and playoffs are selectable',()=>{const games=[{season:'2026',week:'19',game_type:'WC',gameday:'2027-01-09'}];assert.deepEqual(chooseCurrent(games,new Date('2027-01-08')),{season:2026,week:19});});
test('UTC Tuesday during Monday Night Football stays in the current week',()=>{assert.equal(chooseCurrent(fixture().schedule,new Date('2026-09-22T01:00:00Z')).week,2);assert.equal(chooseCurrent(fixture().schedule,new Date('2026-09-22T09:59:00Z')).week,2);assert.equal(chooseCurrent(fixture().schedule,new Date('2026-09-22T10:00:00Z')).week,3);});
test('current-week results cannot enter the sample',()=>{const p=boardFixture()[0];assert.equal(p.details.sample.length,2);assert.equal(p.details.stats.touches_pg,18);assert.equal(p.details.cheat_code.td_debt.actual,1);assert.ok(p.details.sample.every(g=>g.gameId!=='2026_02_B_A'));});
test('uncompleted games cannot enter a future-week sample',()=>{const f=fixture();const ps=boardFixture({week:3,pbp:f.pbp.filter(p=>!(p.game_id==='2026_02_B_A'&&p.desc==='END GAME'))});assert.equal(ps[0].details.sample.length,2);});
test('future rosters cannot retroactively change the selected team',()=>{const f=fixture();const ps=boardFixture({rosters:[f.roster,{...f.roster,week:'3',team:'C'}]});assert.equal(ps[0].team,'A');});
test('inactive players and teams on bye do not get invented matchups',()=>{const f=fixture();assert.equal(boardFixture({rosters:[{...f.roster,status:'RES'}]}).length,0);assert.equal(boardFixture({rosters:[{...f.roster,team:'C'}]}).length,0);});
test('zero-touch offensive appearances count when snap data exists',()=>{const f=fixture(),weekly=f.weekly.filter(p=>p.game_id!=='2026_01_A_B'),pbp=f.pbp.filter(p=>p.game_id!=='2026_01_A_B'||p.desc==='END GAME');const p=boardFixture({weekly,pbp,snaps:[{game_id:'2026_01_A_B',pfr_player_id:'pfr1',team:'A',offense_snaps:'5',offense_pct:'.1'}]})[0];assert.equal(p.details.sample.length,2);assert.equal(p.details.stats.touches_pg,6);});
test('a missing weekly row with actual plays is not fabricated as zero',()=>{const f=fixture(),p=boardFixture({weekly:f.weekly.filter(p=>p.game_id!=='2026_01_A_B'),snaps:[{game_id:'2026_01_A_B',pfr_player_id:'pfr1',team:'A',offense_snaps:'5',offense_pct:'.1'}]})[0];assert.equal(p.details.sample.length,1);});
test('missing charting creates no box or coverage data',()=>{const p=boardFixture()[0];assert.deepEqual(p.details.cheat_code.box,[]);assert.equal(p.details.coverage.chartedGames.length,0);});
test('zero placeholder defenders do not count as a light box',()=>{const p=boardFixture({chart:[{nflverse_game_id:'2025_18_A_B',play_id:'1',defenders_in_box:'0'}]})[0];assert.deepEqual(p.details.cheat_code.box,[]);});
test('NGS missing coverage is null, with explicit count',()=>{const p=boardFixture({market:'rush_yds'})[0];assert.equal(p.details.stats.rush_debt,null);assert.equal(p.details.stats.ngs_rush_games,0);});
test('NGS joins only sampled weeks and excludes season aggregate rows',()=>{const p=boardFixture({market:'rush_yds',ngs:{rushing:[{player_gsis_id:'p1',season:'2026',season_type:'REG',week:'1',expected_rush_yards:'110',rush_yards:'100',rush_yards_over_expected:'-10'},{player_gsis_id:'p1',season:'2026',season_type:'REG',week:'0',expected_rush_yards:'1000',rush_yards:'100'},{player_gsis_id:'p1',season:'2026',season_type:'REG',week:'2',expected_rush_yards:'800',rush_yards:'999'}]}})[0];assert.equal(p.details.stats.rush_debt,10);assert.equal(p.details.stats.ngs_rush_games,1);});
test('NGS debt uses published RYOE when its tracked population differs from all rushing yards',()=>{const p=boardFixture({market:'rush_yds',ngs:{rushing:[{player_gsis_id:'p1',season:'2026',season_type:'REG',week:'1',expected_rush_yards:'80',rush_yards:'120',rush_yards_over_expected:'25'}]}})[0];assert.equal(p.details.stats.rush_debt,-25);assert.equal(p.details.stats.ngs_rush_over_expected,25);assert.equal(p.projected,80);});
test('every configured external data source is independent',()=>{for(const type of Object.keys(DATASETS))assert.match(datasetUrl(type,2026),/^https:\/\/github\.com\/nflverse\/nflverse-data\/releases\/download\//);});
test('invalid season/week and traversal strings fail before data access',()=>{for(const q of [{week:2},{season:2026},{season:2026,week:23},{season:'../',week:1},{market:'fake'},{view:'fake'}])assert.throws(()=>validateQuery(q),{status:400});});
async function temp(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'independent-nfl-test-'));t.after(async()=>{assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));await fs.rm(dir,{recursive:true,force:true});});return dir;}
test('provider retains verified raw data and original timestamp during outage',async t=>{const dir=await temp(t);let now=1000000000000,offline=false;const csv='game_id,season,week\ntest,2026,1\n';const provider=new Provider({dir,now:()=>now,fetcher:async()=>{if(offline)throw Error('offline');return new Response(gzipSync(csv),{headers:{etag:'fixture-v1'}});}});const live=await provider.load('schedule');now+=3600000;offline=true;const stale=await provider.load('schedule');assert.deepEqual(stale.rows,live.rows);assert.equal(stale.meta.fetchedAt,live.meta.fetchedAt);assert.equal(stale.meta.stale,true);assert.match(stale.meta.sha256,/^[0-9a-f]{64}$/);});
test('provider uses conditional requests and preserves download time on 304',async t=>{const dir=await temp(t);let now=1000000000000,calls=0;const provider=new Provider({dir,now:()=>now,fetcher:async(url,opts)=>{calls++;if(calls===2){assert.equal(opts.headers['If-None-Match'],'v1');return new Response(null,{status:304});}return new Response(gzipSync('game_id,season\ng,2026'),{headers:{etag:'v1'}});}});const first=await provider.load('schedule');now+=3600000;const second=await provider.load('schedule');assert.equal(first.meta.fetchedAt,second.meta.fetchedAt);assert.notEqual(first.meta.checkedAt,second.meta.checkedAt);});
test('an unavailable optional dataset returns missing, never simulated rows',async t=>{const provider=new Provider({dir:await temp(t),fetcher:async()=>new Response('',{status:404})});const d=await provider.load('participation',2026,{optional:true});assert.deepEqual(d.rows,[]);assert.equal(d.meta.available,false);});
