import test from 'node:test';
import { isReportedOut,SportsStore } from '../lib/sports/source.mjs';
import assert from 'node:assert/strict';
import { query,SPORTS,SOCCER_LEAGUES } from '../lib/sports/config.mjs';
import { fields,normalizeSummary,soccerMinutes } from '../lib/sports/normalize.mjs';
import { predict,backtest,injuryWorkloads,resultFor } from '../lib/sports/model.mjs';
import { selectMatchupRows,matchupAdjustment } from '../lib/mlb/matchup.mjs';
const sample=(sport='nba')=>Array.from({length:18},(_,i)=>{const date=new Date(Date.UTC(2026,1,i+1)).toISOString(),stats={points:20+i%4,rebounds:6,assists:5,threePointFieldGoalsMade:2,steals:1,blocks:1,turnovers:2,goals:1,shotsTotal:3,blockedShots:2,hits:2,saves:25,totalGoals:1,goalAssists:1,totalShots:3,shotsOnTarget:1,foulsCommitted:2,yellowCards:0,powerPlayTimeOnIce:2,wonCorners:5};const players=['a','b','c'].map((id,j)=>({id,player:id,teamId:j===2?'B':'A',opponentId:j===2?'A':'B',position:sport==='nba'?'G':'C',minutes:30,stats:{...stats},home:j!==2,starter:true}));return {game:{id:String(i),date,complete:true,state:'post'},players,teams:[{id:'A',opponentId:'B',home:true,stats:{...stats,points:100},minutes:240,pace:100},{id:'B',opponentId:'A',home:false,stats:{...stats,points:100},minutes:240,pace:102}]};});
const input=()=>({sport:'nba',market:'points',history:sample(),target:{date:'2026-02-20T23:00:00Z',state:'pre'},player:{id:'a',teamId:'A',opponentId:'B',position:'G',home:true,starter:true,availability:{status:'No injury listing',stale:false}},weather:{status:'available',indoor:true}});
test('all requested soccer competitions and popular sport markets are registered',()=>{assert.equal(Object.keys(SOCCER_LEAGUES).length,7);for(const sport of Object.keys(SPORTS))assert.ok(Object.keys(SPORTS[sport].markets).length>=7);assert.throws(()=>query({sport:'nba',date:'2026-02-30'}));assert.throws(()=>query({sport:'soccer',league:'anything'}));});
test('box score parsing distinguishes missing, zero, and made-attempted stats',()=>{const r=fields(['minutes','points','fieldGoalsMade-fieldGoalsAttempted','blocks'],['12:30','0','2-5','—']);assert.equal(r.minutes,12.5);assert.equal(r.points,0);assert.equal(r.fieldGoalsAttempted,5);assert.equal(r.blocks,null);});
test('summary date comes from competition and team identity is retained',()=>{const d=normalizeSummary({header:{id:'123',competitions:[{date:'2026-02-01T20:00Z',status:{type:{completed:true,state:'post'}},competitors:[{homeAway:'home',team:{id:'1',displayName:'A'}},{homeAway:'away',team:{id:'2',displayName:'B'}}]}]}},'nba');assert.equal(d.game.date,'2026-02-01T20:00Z');assert.equal(d.game.home.id,'1');});
test('soccer minutes account for substitutions and missing participation is not a full match',()=>{const player={athlete:{id:'a'},starter:true,subbedOut:true,stats:[{name:'appearances',value:1}]};assert.equal(soccerMinutes(player,[{type:{text:'Substitution'},clock:{value:3600},participants:[{athlete:{id:'b'}},{athlete:{id:'a'}}]}]),60);assert.equal(soccerMinutes(player,[]),null);assert.equal(soccerMinutes({...player,stats:[{name:'appearances',value:0}]},[]),0);});
test('selected and future results never affect a player forecast',()=>{const x=input(),a=predict(x),future=sample()[0];future.game.date=x.target.date;future.players[0].stats.points=10000;const b=predict({...x,history:[...x.history,future]});assert.equal(a.point,b.point);assert.ok(a.point>0);assert.equal(a.lean,null);assert.ok(a.benchmark.probability.over>=0&&a.benchmark.probability.over<=1);});
test('injury status withholds a forecast; missing inputs are not zero',()=>{const x=input();assert.equal(predict({...x,player:{...x.player,availability:{status:'Out',unavailable:true}}}).point,null);assert.equal(predict({...x,history:[]}).point,null);assert.equal(resultFor({stats:{points:0},minutes:20},{complete:true},SPORTS.nba.markets.points).actual,0);assert.equal(resultFor({stats:{},minutes:20},{complete:true},SPORTS.nba.markets.points).status,'missing');assert.equal(resultFor({stats:{points:0},minutes:0},{complete:true},SPORTS.nba.markets.points).status,'did_not_play');});
test('confirmed same-role teammate absence changes workload conservatively',()=>{const x=input(),roster=[{...x.player,player:'A'},{...x.player,id:'b',player:'B',availability:{status:'Out',unavailable:true,stale:false}}],impact=injuryWorkloads(roster,x.history,'nba').get('a');assert.ok(impact.delta>0&&impact.delta<=5);assert.ok(predict({...x,injury:impact}).point>predict(x).point);assert.equal(injuryWorkloads(roster.map(p=>({...p,availability:{status:'Questionable',concern:true}})),x.history,'nba').size,0);});
test('soccer weather and NHL power play are supporting factors, with indoor weather neutral',()=>{const x=input(),history=sample('soccer'),p={...x.player,position:'F'};const a=predict({...x,sport:'soccer',market:'shots',history,player:p,weather:{status:'available',indoor:false,windMph:35,temperatureF:100}}),b=predict({...x,sport:'soccer',market:'shots',history,player:p});assert.ok(a.point<b.point);assert.equal(predict(x).effects.weather.factor,1);});
test('rolling evaluation excludes selected-game starting status and current injury data',()=>{const h=sample('soccer'),first=backtest({sport:'soccer',market:'shots',history:h});h.forEach(g=>g.players.forEach(p=>p.starter=false));const second=backtest({sport:'soccer',market:'shots',history:h});assert.equal(first.mae,second.mae);assert.ok(first.n>0);});
const stat=(season,code,pa,hits,pitcher=8)=>({season:String(season),gameType:'R',split:{code},pitcher:{id:pitcher},stat:{plateAppearances:pa,hits,atBats:pa,homeRuns:1,strikeOuts:2,baseOnBalls:0,doubles:0,triples:0,totalBases:hits+3}});
test('MLB historical matchup excludes current-year and career-total leakage',()=>{const person={stats:[{type:{displayName:'statSplits'},splits:[stat(2025,'vl',100,30),stat(2026,'vl',100,100)]},{type:{displayName:'vsPlayer'},splits:[stat(2024,'',12,3),stat(2026,'',15,15),stat(2025,'',12,8,99)]},{type:{displayName:'vsPlayerTotal'},splits:[stat(2024,'',5000,5000)]}]};const r=selectMatchupRows(person,{year:2026,pregame:false,pitcherId:8});assert.equal(r.hand.length,1);assert.equal(r.versus.length,1);assert.equal(r.versus[0].stat.hits,3);});
test('MLB handedness selects the correct split, limits head-to-head influence and preserves missing stats',()=>{const i={pitcherId:8,pitcherHand:'L',hand:[stat(2025,'vl',100,50),stat(2025,'vr',200,20)],versus:[stat(2025,'',3,3)],sources:[]};const a=matchupAdjustment(i,'hits',1,.25),b=matchupAdjustment({...i,pitcherHand:'R'},'hits',1,.25);assert.ok(a.after>b.after);assert.ok(Math.abs(a.factor-1)<=.100001);assert.ok(Math.abs(a.components[1].fullGameEffect)<=.025);assert.equal(matchupAdjustment({...i,pitcherHand:null},'hits',1,.25).factor,1);assert.equal(matchupAdjustment(i,'runs',1,.25).components[0].plateAppearances,0);});

test('source suspension status is unavailable and empty diagnostics do not imply perfect accuracy',()=>{for(const status of ['Out','Inactive','IR','Suspension','Suspended'])assert.equal(isReportedOut(status),true);assert.equal(isReportedOut('Day-To-Day'),false);const r=backtest({sport:'nhl',market:'shots',history:[]});assert.equal(r.n,0);assert.equal(r.mae,null);assert.equal(r.brier,null);});

test('transient uncached source failure retries once and records the successful receipt',async()=>{let calls=0;const provider={read:async()=>{calls++;if(calls===1)throw Error('fetch failed');return {payload:{events:[]},url:'https://example.test/feed',sha256:'hash',stale:false};}},sources=[],store=new SportsStore({provider,archive:{}});await store.get('https://example.test/feed',{sources});assert.equal(calls,2);assert.equal(sources.length,1);assert.equal(sources[0].stale,false);});
