const CALCULATOR_BASE = '/betting-calculators';
const TOOLS_BASE = '/betting-tools';

const calculators = [
  { slug: 'arbitrage-hedge-bet', title: 'Sports Betting Arbitrage & Hedge Calculator', short: 'Split a bankroll across opposing prices and compare the return on each outcome.', tool: 'arbitrage', sections: [
    ['How an arbitrage bet works', 'A betting arbitrage exists when the implied probabilities of every outcome add up to less than 100%. That gap can let you cover both sides at different sportsbooks and finish with the same positive return whichever side wins. The calculator sizes each stake from the odds you enter and shows whether the combined market clears the break-even point.', 'Use decimal odds internally or enter American prices such as +120 and -110. The calculation assumes both wagers are accepted at the displayed price, settle under matching rules, and cover every possible outcome.'],
    ['Hedge bet sizing formula', 'For two outcomes, the arbitrage percentage is 1 ÷ decimal odds A plus 1 ÷ decimal odds B. When that total is below one, the ideal stakes are proportional to each outcome’s inverse price. For a hedge against an existing wager, enter the first stake as the bankroll and the calculator balances the gross payout on both sides.', 'For example, +120 and +110 convert to decimal odds of 2.20 and 2.10. Their implied probabilities total about 93.0%, leaving an estimated 7.0% gross arbitrage margin before limits, fees, or price movement.'],
    ['Check the ticket before placing it', 'Compare the event, market period, overtime rules, player participation rules, and settlement source before hedging. A stale line, rejected wager, stake limit, or different market definition can remove the apparent edge. Enter the prices available to you now and recalculate if either price moves.']
  ], faqs: [['How do I calculate an arbitrage hedge bet?', 'Convert both American odds to decimal odds, add their reciprocal implied probabilities, and compare the sum with 1. If it is below 1, allocate stakes in proportion to the reciprocal prices so each winning outcome returns the same amount.'], ['Can an arbitrage bet guarantee a profit?', 'The arithmetic shows a profit only if every wager is accepted and the markets settle consistently at the entered odds. Limits, voids, changing prices, and account restrictions can change the result.'], ['What does a negative arbitrage result mean?', 'The combined implied probability is at least 100%, so the quoted pair cannot lock in a positive return at the entered stake.'] ] },
  { slug: 'expected-value', title: 'Expected Value (EV) Sports Betting Calculator', short: 'Estimate a bet’s expected profit from your stake, price, and win probability.', tool: 'ev', sections: [
    ['What expected value means in sports betting', 'Expected value is the average net result of repeating the same wager many times under the same probability and price assumptions. A positive expected value bet has a price that pays more than its estimated chance warrants; a negative EV bet pays too little. EV describes a long-run average, not a prediction for the next game.', 'Your probability estimate is the key assumption. It can come from a model, a fair market price, or your own research, but the calculator does not verify that estimate.'],
    ['Expected value formula for a wager', 'For a win-or-lose bet, EV equals the probability of winning multiplied by the profit if it wins, minus the probability of losing multiplied by the stake. At +110, a $100 winning bet earns $110 profit. If your estimated win probability is 50%, EV is 0.50 × $110 − 0.50 × $100 = $5.', 'A 5% expected return on stake means an estimated $5 long-run profit per $100 risked under those inputs. It does not mean each $100 wager is likely to win $5.'],
    ['Use fair probabilities with care', 'A sportsbook’s implied probability includes margin. Comparing your estimate with a no-vig probability can help separate the market’s opinion from the bookmaker’s hold, but different markets and books can disagree. Recheck the odds near placement and record the source and time behind your estimate.']
  ], faqs: [['How do you calculate EV for a sports bet?', 'Multiply the win probability by the profit on a win, then subtract the loss probability multiplied by the stake. Convert American odds to net profit before applying the formula.'], ['What is a good expected value percentage?', 'Any positive estimate is above break-even mathematically, but small edges can be overwhelmed by probability error, price changes, or limits. There is no universally reliable cutoff.'], ['Does positive EV mean the bet will win?', 'No. A positive EV bet can lose. Expected value is an average across many comparable wagers, and the actual result can vary substantially.']] },
  { slug: 'free-bet-conversion', title: 'Free Bet Conversion Calculator', short: 'Estimate the cash value of a stake-not-returned bonus bet using an opposing hedge.', tool: 'freebet', sections: [
    ['How to convert a free bet to cash', 'Most sportsbook bonus bets are stake-not-returned: if the selection wins, the sportsbook pays only the profit portion. To estimate conversion value, use the token on one side of a market and place a cash hedge on the opposing side. The calculator balances the two net outcomes using the odds you enter.', 'A $100 token at +200 has $200 in potential profit, not a $300 return. An opposing cash wager can secure part of that value whichever result occurs.'],
    ['Free bet conversion formula', 'If the free-bet odds are decimal D and the opposing odds are decimal H, the balancing hedge stake is token value × (D − 1) ÷ H. The guaranteed cash proceeds are the hedge’s profit when the token side loses. Divide those proceeds by the token amount to estimate conversion percentage.', 'This is an estimate for a two-outcome market with no push, void, cash-out, or correlated result. Exact sportsbook promotion terms determine whether the token qualifies and when winnings become withdrawable.'],
    ['Improve a bonus bet conversion', 'Compare multiple eligible markets and look for prices that let the bonus-bet side generate meaningful profit without an expensive opposing hedge. Avoid parlays or markets with unmatched settlement rules unless you have modeled those outcomes separately. Enter the actual token value and current opposing price before using a promotion.']
  ], faqs: [['Are free bets returned if they lose?', 'Usually a bonus bet token is consumed whether it wins or loses. Promotion rules vary, so check whether the token is stake-not-returned and whether winnings have rollover or withdrawal conditions.'], ['What is a good free bet conversion rate?', 'A higher conversion percentage means more estimated cash value per token dollar, but the available odds and promotion terms determine what is practical. No fixed rate is guaranteed.'], ['Why is a hedge used to convert a free bet?', 'The hedge creates a second outcome that can return cash when the bonus-bet selection loses, while the token’s profit pays when it wins. Balancing those outcomes estimates a cash conversion.']] },
  { slug: 'half-point', title: 'Half-Point Betting Calculator', short: 'Compare a spread or total before and after buying a half point.', tool: 'halfpoint', sections: [
    ['What a half point changes', 'A half point moves a point spread or game total by 0.5. That small move can change a bet from a loss to a win when the final margin or score lands on a key number. In football, numbers such as 3 and 7 appear more often than many other margins, so their value depends on the sport and market.', 'The value of buying a half point is not constant. It depends on how likely the moved line is to cross the final result and on the worse odds charged for the alternate line.'],
    ['Compare the price and probability', 'Enter your estimated cover probability at the current line, the probability added by moving the line, and both available prices. The calculator estimates expected value at each price and isolates the change. It treats the added probability as an input, so it does not assume every half point is worth the same amount.', 'For example, buying from -110 to -125 costs extra juice. The move is worthwhile under your assumptions only when the added cover probability compensates for that price change.'],
    ['Use sport-specific estimates', 'Key numbers differ between NFL spreads, basketball spreads, and totals. Use historical scoring or a calibrated model for the league and market you are evaluating. The estimate here is a decision aid; it cannot infer the probability of landing on the key number from the half-point move alone.']
  ], faqs: [['Is every half point worth the same amount?', 'No. A half point is more valuable near frequently occurring score margins or totals, and less valuable where final results rarely land. The price also changes its value.'], ['What is a key number in spread betting?', 'A key number is a final margin or total that occurs often enough to affect how many bets win, lose, or push. Common examples vary by sport and market.'], ['How do I know whether buying a half point is worth it?', 'Compare the added probability of covering the alternate line with the extra cost shown in its odds. Use estimates relevant to the league and market.']] },
  { slug: 'hold', title: 'Sports Betting Hold Calculator', short: 'Calculate the estimated hold and no-vig probabilities from both sides of a market.', tool: 'hold', sections: [
    ['Sportsbook hold and overround', 'Hold, often called overround or vig in a quoted market, is the amount by which the implied probabilities across outcomes exceed 100%. Convert each side’s odds into implied probability and add them. A 104% total indicates a 4% overround estimate for that market.', 'This is a price-based estimate. A sportsbook’s realized hold over a period depends on the bets it accepts, customer outcomes, bonuses, and limits. It is not necessarily the book’s final profit margin.'],
    ['Remove the margin to compare fair probabilities', 'A proportional no-vig estimate divides each outcome’s implied probability by the total implied probability. If +100 is offered on both sides, each side implies 50% and the market has no overround. At -110 on both sides, each side implies about 52.38%, for a combined 104.76%.', 'After removing that margin proportionally, each side’s estimated fair probability is 50%. Other margin-removal methods exist, particularly in multi-outcome markets, so state the method when comparing prices.'],
    ['Use hold to compare prices', 'Lower overround markets generally make it less expensive to take a position, though the best price on each side can come from different books. Compare equivalent markets, including regulation time, overtime, and tie rules. A low hold does not indicate which side is more likely to win.']
  ], faqs: [['How do I calculate sportsbook hold?', 'Convert each outcome’s American odds to implied probability, add the probabilities, and subtract 100%. The result is the market’s estimated overround.'], ['Is hold the same as profit?', 'No. Hold is a quoted-market estimate from prices. Realized sportsbook profit depends on actual wagers and outcomes over time.'], ['What is a low hold in sports betting?', 'A lower overround means the quoted implied probabilities add closer to 100%, which generally indicates less pricing margin in that market.']] },
  { slug: 'implied-probability', title: 'Sports Betting Implied Probability Calculator', short: 'Convert American odds into implied win probability and decimal odds.', tool: 'implied', sections: [
    ['What implied probability tells you', 'Implied probability is the win percentage associated with a price at break-even. It lets you translate American odds into a probability that is easier to compare with a forecast. The quoted percentage includes sportsbook margin unless you remove the vig across all outcomes.', 'At -150, a bettor risks $150 to win $100, so the break-even probability is 150 ÷ (150 + 100), or 60%. At +150, the break-even probability is 100 ÷ (150 + 100), or 40%.'],
    ['American odds probability formula', 'For positive American odds A, implied probability is 100 ÷ (A + 100). For negative odds −A, use A ÷ (A + 100). Decimal odds are 1 plus the implied profit per unit staked and make it easier to combine prices.', 'The calculator also shows decimal odds so you can compare a US price with decimal or fractional formats without changing the underlying payout.'],
    ['Separate break-even chance from true chance', 'A 60% break-even probability does not mean an event has a 60% chance of occurring. It means a bettor would need to win 60% of equal-sized wagers at that price to break even before accounting for pushes, taxes, or bonuses. Compare the number with a credible independent probability estimate.']
  ], faqs: [['How do you convert -110 odds to implied probability?', 'For negative American odds, divide the absolute odds by the absolute odds plus 100. At -110, that is 110 ÷ 210, or about 52.38%.'], ['Do implied odds include the vig?', 'Yes. A single side’s implied probability is calculated from the listed price, which usually includes the sportsbook’s margin. Remove the vig using all outcomes in the market.'], ['What is the difference between implied probability and win probability?', 'Implied probability is the break-even rate associated with the price. Win probability is an estimate of how likely the outcome actually is. They can differ.']] },
  { slug: 'kelly-criterion', title: 'Kelly Criterion Sports Betting Calculator', short: 'Estimate a bankroll fraction from your odds and your own win probability.', tool: 'kelly', sections: [
    ['Kelly staking for sports bets', 'The Kelly Criterion estimates the bankroll fraction that maximizes long-run logarithmic growth when the odds and win probability are known. It does not identify good bets by itself; it converts an assumed edge into a stake size. If your estimated probability is below break-even, full Kelly returns a zero stake.', 'Because probability estimates are uncertain, many bettors use half Kelly or quarter Kelly. Fractional Kelly reduces the recommended stake and the size of bankroll swings, while also reducing modeled growth.'],
    ['Kelly formula and inputs', 'For net decimal payout b and win probability p, the full Kelly fraction is (b × p − q) ÷ b, where q = 1 − p. Enter the bankroll, offered American odds, estimated win probability, and Kelly fraction. The calculator reports the suggested dollar stake and the full-Kelly percentage.', 'A small change in estimated win probability can cause a large change in stake size. Use a conservative probability estimate and recalculate when the price moves.'],
    ['Bankroll risk and practical limits', 'Kelly assumes a repeatable edge, accurate probabilities, and a bankroll that can tolerate losses. Those assumptions are difficult to satisfy in real betting. Fractional Kelly and a maximum bet limit can reduce exposure, but neither guarantees profit or prevents a losing run.']
  ], faqs: [['What is the Kelly Criterion formula?', 'For a binary wager, the full Kelly fraction is (b × p − q) ÷ b, where b is net payout per unit, p is win probability, and q is loss probability.'], ['Should I use full Kelly for sports betting?', 'Full Kelly is sensitive to probability errors and can produce volatile stakes. Fractional Kelly uses less bankroll per bet, though the appropriate risk level is personal.'], ['Why does Kelly recommend no bet?', 'The estimated win probability does not exceed the break-even threshold implied by the price, so the calculated growth-maximizing stake is zero.']] },
  { slug: 'no-vig-fair-odds', title: 'No-Vig Fair Odds Calculator', short: 'Remove the sportsbook margin from a two-way market to estimate fair odds.', tool: 'novig', sections: [
    ['No-vig odds and fair probability', 'Sportsbook odds include a margin that makes the implied probabilities across outcomes add to more than 100%. A no-vig calculator removes that excess and rescales the outcome probabilities to total 100%. The resulting fair odds are a market-based estimate, not a guarantee or a prediction.', 'For a two-way market priced -110 on both sides, each raw probability is about 52.38%. Proportional normalization produces a 50% no-vig probability on each side, equivalent to fair odds of +100.'],
    ['How the no-vig calculation works', 'First convert both prices to implied probabilities. Then divide each probability by the sum across outcomes. Convert the normalized probability back to American odds to get the fair price. This calculator uses proportional normalization, one common method for a two-outcome market.', 'For three-way markets, different methods for allocating the margin can produce different fair probabilities. Use a method suited to the market and disclose it when comparing model outputs.'],
    ['Compare your number with fair odds', 'If your estimated win probability is higher than the no-vig probability, that may suggest a price difference worth researching. Check that your model and the market refer to the same outcome, time period, and settlement rules. A market consensus is a reference point, not ground truth.']
  ], faqs: [['How do you remove vig from betting odds?', 'Convert every side to implied probability, divide each by the market probability total, and convert the normalized probabilities back into odds. This page uses proportional normalization.'], ['Are no-vig odds truly fair?', 'They are a margin-adjusted estimate based on the prices entered. The result depends on the market and the chosen margin-removal method.'], ['What are fair odds for -110 on both sides?', 'Proportional no-vig conversion makes each side 50%, equivalent to +100 fair odds in a two-outcome market.']] },
  { slug: 'odds-converter', title: 'Sports Betting Odds Converter', short: 'Convert American odds to decimal odds, fractional odds, and implied probability.', tool: 'odds', sections: [
    ['Convert American, decimal, and fractional odds', 'Odds formats describe the same payout in different ways. American odds use positive and negative prices, decimal odds show total return per unit staked, and fractional odds express profit relative to stake. This odds converter translates an American price into the other formats and its break-even probability.', 'For example, +150 American odds equal decimal 2.50 and fractional 3/2. A $10 winning bet at those odds returns $25 in total: $15 profit plus the original $10 stake.'],
    ['Read the payout, not only the sign', 'Positive American odds show the profit from a $100 stake. Negative odds show the amount you need to risk to earn $100 profit. Decimal odds include the stake in total return, while fractional odds do not.', 'Use the probability output as a break-even figure. It includes any market margin embedded in that single price and may not represent the event’s true likelihood.'],
    ['When odds conversion is useful', 'A consistent format makes it easier to compare sportsbooks, calculate parlay payouts, and evaluate expected value. Convert each leg before multiplying parlay prices, and use the current odds rather than a stored line when planning a wager.']
  ], faqs: [['How do I convert American odds to decimal odds?', 'For positive odds, divide the price by 100 and add 1. For negative odds, divide 100 by the absolute price and add 1.'], ['What does +150 mean in betting?', 'A $100 stake at +150 wins $150 profit, plus the $100 stake returned, for $250 total return. The break-even probability is 40%.'], ['What is the difference between decimal odds and fractional odds?', 'Decimal odds include the stake in the displayed total return. Fractional odds show profit relative to stake.']] },
  { slug: 'parlay', title: 'Sports Betting Parlay Calculator', short: 'Calculate combined parlay odds, potential payout, and break-even probability.', tool: 'parlay', sections: [
    ['How parlay odds are combined', 'A parlay combines multiple selections into one wager. Every leg generally must win for a standard parlay to pay. Convert each leg’s American odds to decimal form and multiply the decimals to get combined odds, total return, and profit.', 'A three-leg parlay at decimal prices 1.91, 2.00, and 1.80 has combined odds of about 6.88. A $10 winning ticket returns about $68.76 including the stake.'],
    ['Parlay payout and probability', 'When legs are independent, multiply their estimated win probabilities to estimate the chance every leg wins. If they are correlated, multiplying probabilities is not valid; sportsbooks may also change the payout for same-game parlays. Enter the estimated probability for each leg to see a simple independent-leg expected value estimate.', 'The combined break-even probability is the reciprocal of the parlay’s decimal odds. A parlay can offer a large payout and still have a low chance of winning.'],
    ['Understand parlay risk', 'Adding a leg usually increases the payout and lowers the probability the full ticket wins. One losing leg can erase otherwise correct picks. Compare the offered payout with a realistic joint-probability estimate and account for void-leg rules.']
  ], faqs: [['How do you calculate parlay odds?', 'Convert each selection to decimal odds and multiply the decimal prices. Convert the result back to American odds if desired.'], ['Does a parlay need every leg to win?', 'A standard parlay normally requires every leg to win, though voids and pushes can reduce the ticket to a smaller parlay under house rules.'], ['Are same-game parlay legs independent?', 'Often they are correlated. A simple product of individual probabilities can misstate the chance of a same-game combination, and the sportsbook may adjust the payout.']] },
  { slug: 'point-spread', title: 'Point Spread Bet Calculator', short: 'Settle a point spread wager and calculate the profit or loss from the final score.', tool: 'spread', sections: [
    ['How a point spread wager settles', 'A point spread adjusts the final score to create a handicap. Add the selected team’s spread to its final score and compare the adjusted score with the opponent’s score. A higher adjusted score is a win, an equal score is a push, and a lower score is a loss.', 'If a team wins 24–20 and was favored by -3.5, its adjusted margin is 0.5 and the spread bet wins. At -4, the adjusted margin is zero and the wager pushes, subject to the sportsbook’s rules.'],
    ['Calculate spread bet payout', 'For a winning wager, American odds determine net profit and the original stake is returned. A losing wager loses the stake. A push generally returns the stake. Enter the favorite’s spread as a negative number and the underdog’s as a positive number.', 'Alternative spreads may use different prices for the same matchup. Calculate each ticket using the actual line and odds on the bet slip.'],
    ['Half-point lines and pushes', 'Half-point spreads avoid pushes on a standard final score, while whole-number spreads can push when the adjusted scores tie. Quarter-point Asian lines split the stake into two neighboring lines and need separate settlement math. This calculator covers a single spread line.']
  ], faqs: [['How do I calculate a point spread bet?', 'Add the selected team’s spread to its score, then compare that adjusted score with the opponent’s. A win, tie, or loss determines the settlement.'], ['What happens when a spread bet pushes?', 'On a standard single wager, a push typically returns the stake. Check the sportsbook’s rules for parlays or special markets.'], ['What does -3.5 mean on a point spread?', 'The favorite must win by at least four points for a -3.5 wager to cover. The half point prevents a tie at exactly three points.']] },
  { slug: 'poisson', title: 'Poisson Distribution Sports Betting Calculator', short: 'Estimate exact, over, and under probabilities from an average event count.', tool: 'poisson', sections: [
    ['Poisson distribution in sports betting', 'A Poisson model estimates the probability of observing a count when events occur independently at a stable average rate. Bettors use it as a starting point for count statistics such as goals, made shots, or player events. The mean is often denoted by lambda (λ).', 'The model can be a poor fit when opportunities vary, events depend on game state, player minutes change, or observations are overdispersed. A recent average alone does not guarantee a reliable forecast.'],
    ['Calculate an exact or threshold probability', 'The probability of exactly k events is e⁻λ × λᵏ ÷ k!. An “at least” probability sums the probabilities from k upward, while an “at most” probability sums from zero through k. This calculator converts the selected probability to fair American odds for comparison.', 'With an average of 2.0 events, the probability of exactly two is about 27.1%. The chance of at least two is about 59.4%; those answer different betting questions.'],
    ['Compare a model with sportsbook odds', 'Use a mean that matches the same player, market definition, and expected playing time. Compare the calculated probability with the price’s implied break-even probability after considering market margin. Treat the result as a simple statistical estimate, not a full player projection.']
  ], faqs: [['What does lambda mean in a Poisson calculator?', 'Lambda is the expected average count of events for the observation period, such as expected goals or a player statistic.'], ['Can a Poisson model predict sports outcomes?', 'It can estimate count probabilities under its assumptions, but real sports data may violate those assumptions. It is a simplified model, not a guarantee.'], ['How do I calculate the chance of at least one event?', 'For a Poisson mean λ, the chance of at least one event is 1 − e⁻λ. The calculator also handles other integer thresholds.']] },
  { slug: 'round-robin', title: 'Round Robin Betting Calculator', short: 'Count round robin combinations and estimate total cost and payout.', tool: 'roundrobin', sections: [
    ['What is a round robin bet?', 'A round robin creates a set of smaller parlays from a group of selections. For example, a three-team round robin by 2s makes three two-leg parlays. Each combination is a separate wager, so a round robin can return money when one selection loses if another combination wins.', 'The total ticket cost is the stake per combination multiplied by the number of combinations. Each winning combination pays according to its own parlay odds.'],
    ['Calculate round robin combinations', 'For n selections used k at a time, the number of combinations is n choose k: n! ÷ (k! × (n − k)!). Enter each leg’s odds and the desired combination size to see the count, total stake, and payout if every selected leg wins.', 'With four picks by 2s, there are six parlays. At $5 per combination, the total cost is $30. The maximum payout depends on all six leg pairs and their prices.'],
    ['Round robin risk and settlement', 'A round robin still risks losing every combination when too few picks win. Pushes, voids, and reduced odds change combination settlements under sportsbook rules. This calculator shows the all-picks-win payout and cost; it does not simulate partial results or special parlay rules.']
  ], faqs: [['How many bets are in a round robin?', 'It depends on the number of selections and the number of legs in each combination. Use the combinations formula n choose k.'], ['How is round robin cost calculated?', 'Multiply the number of parlay combinations by the stake per combination. Each combination is a separate wager.'], ['Can a round robin win if one pick loses?', 'Some combinations can still win if they do not include the losing pick. The result depends on which selections win and the round robin structure.']] },
  { slug: 'vig', title: 'Sports Betting Vig Calculator', short: 'Measure sportsbook juice from two prices and see the proportional no-vig odds.', tool: 'vig', sections: [
    ['What vig means in sports betting', 'Vig, short for vigorish, is the bookmaker’s commission embedded in a price. It is also called juice. At -110, you risk $110 to win $100; a symmetric -110 market on both sides implies more than 100% total probability, and that excess is the quoted market margin.', 'Vig is not a fee shown as a separate line item. It affects how much a winning bet pays and the break-even rate needed to profit over time.'],
    ['Calculate juice from market odds', 'Convert both sides to implied probability and add them. The amount above 100% is the estimated overround. The calculator also removes the margin proportionally to display an estimated fair probability and fair American odds for each side.', 'A pair of -110 prices adds to roughly 104.76%, so the market overround is about 4.76%. Proportional no-vig normalization makes the two fair probabilities 50% each.'],
    ['Compare vig across books', 'Shop the same market at multiple sportsbooks and compare the best available prices on both outcomes. A lower vig can improve the long-run price you receive, but line shopping also matters: the odds and the spread or total must both be considered.']
  ], faqs: [['Is vig the same as juice?', 'Yes. Vig and juice both refer to the bookmaker margin built into betting odds.'], ['How much vig is -110?', 'One -110 price implies about 52.38%. Two -110 sides total about 104.76%, a 4.76% market overround.'], ['How can I pay less vig?', 'Compare equivalent market prices across sportsbooks and use the best available odds. Always check that the lines and settlement rules match.']] }
];

const tools = [
  { slug: 'arbitrage', title: 'Sports Betting Arbitrage Tool', short: 'Check two sportsbook prices for a covered, equal-return arbitrage.', tool: 'arbitrage', sections: [
    ['Find a two-way arbitrage opportunity', 'Enter the odds for opposite outcomes and a total bankroll. The arbitrage tool calculates the combined implied probability, tells you whether the pair clears break-even, and splits the stake so both winning outcomes return the same amount.', 'The tool works with prices you supply. It does not scan sportsbooks or retrieve live odds, so confirm both prices directly before placing either side.'],
    ['Read the arbitrage profit estimate', 'When reciprocal decimal odds total less than one, the entered prices imply an arbitrage margin. The displayed profit is before account limits, transaction costs, line movement, and settlement differences. If the total is above one, the pair cannot guarantee a positive return at those prices.'],
    ['Place both sides consistently', 'Verify the event, market period, selection, and rules on both tickets. Place sizes can be limited or prices can move after the first wager. Recalculate from accepted stakes if either book changes the amount or odds.']
  ], faqs: [['Does this arbitrage betting tool scan live odds?', 'No. Enter the current prices you found at the sportsbooks. The page calculates the stake split and estimated result but has no live odds feed.'], ['What makes an arbitrage profitable?', 'The implied probabilities of all outcomes add to less than 100%, before execution costs and settlement risk.'], ['How should I split an arbitrage bankroll?', 'Allocate stakes in proportion to each outcome’s reciprocal decimal odds so the gross return is balanced.']] },
  { slug: 'boosts', title: 'Sports Betting Odds Boost Calculator', short: 'Compare a boosted price with the original odds and estimate the change in expected value.', tool: 'boosts', sections: [
    ['Evaluate a sportsbook odds boost', 'An odds boost improves the payout on an eligible selection, but the promotion may have a stake cap, minimum odds, or token requirement. Enter the original price, boosted price, your estimated win probability, and stake to compare payout and expected value.', 'A larger payout does not automatically make a bet positive EV. The estimated chance of winning and the promotion rules still matter.'],
    ['Calculate the boost value', 'The boost percentage compares the net profit at the boosted price with the profit at the original price. Expected value is calculated separately for each price using your probability estimate. The difference shows the estimated value added by the price change for the entered stake.', 'For example, improving +100 to +150 increases the profit on a $20 win from $20 to $30. If the bet loses, the stake is still lost unless the promotion includes insurance.'],
    ['Read the promotion terms', 'Check whether the boost applies to singles or parlays, whether odds must meet a minimum, and whether winnings include the returned stake. Some offers cap the eligible stake or pay bonus funds instead of cash. Use the qualifying price and stake in the calculator.']
  ], faqs: [['How do I calculate the value of an odds boost?', 'Compare the net profit and expected value at the original and boosted odds for the same stake and estimated win probability.'], ['Are boosted bets always profitable?', 'No. A boost improves the payout, but the selection can still be overpriced relative to its actual chance of winning.'], ['Does the boost percentage include my stake?', 'This calculator compares net profit, excluding the returned stake, so the increase measures the extra win profit. Check the sportsbook’s promotion terms.']] },
  { slug: 'free-bet-converter', title: 'Free Bet Conversion Tool', short: 'Estimate cash conversion from a bonus bet and an opposing cash hedge.', tool: 'freebet', sections: [
    ['Turn a bonus bet into estimated cash value', 'Enter the free-bet amount, its odds, and the opposing side’s odds. The converter balances the bonus-bet profit against a cash wager on the other outcome, then estimates the cash proceeds and conversion percentage.', 'This assumes a stake-not-returned token and a two-way market with no push. The sportsbook’s rules determine the actual token value and withdrawal conditions.'],
    ['Choose a market for bonus bet conversion', 'A useful market pairs a good token price with a hedge price that keeps enough value on the opposing side. Compare eligible offerings instead of automatically choosing the longest odds. The highest token payout can require an expensive hedge.', 'Enter the prices available at the time you expect to place both wagers. The estimated conversion can change quickly as either side moves.'],
    ['Check free bet requirements', 'Bonus bets can have expiry dates, odds minimums, sport restrictions, and stake-not-returned rules. Some offers award bonus funds only after a qualifying wager settles. Confirm how the promotion handles pushes, voids, and cash-outs before converting.']
  ], faqs: [['What is a free bet conversion rate?', 'It is the estimated cash value recovered divided by the nominal bonus bet amount. The actual value depends on the offered odds and promotion terms.'], ['What is the hedge bet for a free bet?', 'It is a cash wager on the opposing outcome, sized to balance the free-bet side’s profit if that side wins.'], ['Can I withdraw free bet winnings?', 'Sportsbooks commonly pay winnings rather than the token stake, but eligibility and withdrawal conditions vary by promotion. Read the specific terms.']] },
  { slug: 'low-hold', title: 'Low Hold Sports Betting Tool', short: 'Shop two books for the best price on each side and estimate the combined hold.', tool: 'lowhold', sections: [
    ['Find lower-hold prices across sportsbooks', 'Enter both sides from two books. The tool selects the better price on each outcome, calculates the combined market overround, and compares it with the hold at each individual book. A lower combined hold can come from taking opposite sides at different sportsbooks.', 'Use prices from the same event, period, and market definition. Combining mismatched markets creates a number that does not describe a real two-outcome position.'],
    ['Why low hold matters', 'The vig embedded in odds raises the break-even rate. Shopping for a better price can reduce that cost and improve the expected return of a wager, all else equal. Low hold is a market property; it does not tell you which outcome to select.', 'If each side is -110 at one book, the market overround is about 4.76%. Replacing one side with +100 lowers the combined implied probability total.'],
    ['Use the best available odds', 'The tool uses the top price entered on each side, but availability, limits, and timing may differ. Confirm the line and stake limit at each sportsbook before acting. This page does not connect to a sportsbook or refresh market data.']
  ], faqs: [['What is a low-hold bet?', 'It is a market or pair of prices with a relatively low overround, meaning the implied probabilities add closer to 100%.'], ['Can low hold still lose?', 'Yes. Low hold describes the price margin, not the event outcome. A well-priced wager can still lose.'], ['How does this tool find the best prices?', 'It compares the two prices you enter for each outcome and uses the better one to calculate the combined overround.']] },
  { slug: 'middles', title: 'Sports Betting Middle Calculator', short: 'Check the overlap between an over and under, then see the middle range and ticket outcomes.', tool: 'middle', sections: [
    ['What is a middle bet?', 'A middle pairs wagers on opposite sides of different lines, such as Over 47.5 and Under 51.5. Both wagers win if the final total lands between the lines. Outside that middle window, one side may win and the other lose; pushes can occur on whole-number lines.', 'A middle is not automatically a guaranteed profit. The odds, stakes, and outcomes outside the window determine how much is at risk.'],
    ['Calculate the middle window', 'Enter the lower over line, upper under line, both American odds, and each stake. The tool identifies integer results that fall strictly between the thresholds and estimates net profit if the total lands in the middle. It also shows the one-side outcome profit or loss for results below or above the window.', 'For Over 47.5 and Under 51.5, totals of 48 through 51 win both wagers. The exact range changes with half-point and whole-number lines.'],
    ['Price both sides before betting', 'Different books can offer different prices on opposite sides. Recheck both lines together and confirm that the event and market period match. This calculator models a two-wager total market and does not estimate the probability of landing in the middle.']
  ], faqs: [['How do you calculate a betting middle?', 'Identify results strictly above the over line and strictly below the under line. Those results make both wagers win; then calculate each ticket’s payout from its odds and stake.'], ['Can a middle guarantee profit?', 'Usually not. Outcomes outside the middle can cause one winning wager and one losing wager, and the combined stakes may still create a net loss.'], ['What is the middle range for Over 47.5 and Under 51.5?', 'Integer totals 48, 49, 50, and 51 are above 47.5 and below 51.5, so both wagers win for those totals.']] },
  { slug: 'parlay-builder', title: 'Sports Betting Parlay Builder', short: 'Build a parlay from individual prices and estimated probabilities, then review its payout and expected value.', tool: 'parlaybuilder', sections: [
    ['Build a parlay from your own inputs', 'Add up to four selections by entering each leg’s American odds and your estimated win probability. The builder multiplies the prices and, under an independence assumption, multiplies the probabilities. It reports combined odds, potential return, break-even probability, and estimated expected value.', 'This is a manual planning tool. It does not search sportsbook markets, create a sportsbook ticket, or validate the probability estimates.'],
    ['Compare the parlay price with your estimate', 'A positive expected value result means the combined payout exceeds the calculated break-even price under the probabilities entered. If selections are correlated, use a joint probability rather than multiplying each leg separately. Same-game parlay prices commonly account for correlation.', 'For example, two independent legs each estimated at 55% have a combined probability of 30.25%. Correlated game outcomes can make the true joint chance higher or lower.'],
    ['Keep parlay risk visible', 'Parlays concentrate risk because one losing leg can defeat the full wager. The payout grows with added legs, but the chance of every leg winning generally falls. Compare the offer with a realistic joint model and read the sportsbook’s void-leg rules.']
  ], faqs: [['How many legs can I add?', 'The builder accepts up to four legs on this page. You can include fewer by leaving a leg unchecked.'], ['Does the builder find positive EV parlays?', 'It calculates expected value from the odds and probabilities you enter. It does not scan sportsbook lines or supply independent model estimates.'], ['Can I multiply same-game parlay probabilities?', 'Only if the legs are independent. Related outcomes need a joint probability model, and the sportsbook may price that correlation into the ticket.']] },
  { slug: 'positive-ev', title: 'Positive EV Betting Tool', short: 'Compare a sportsbook price with your win probability to estimate expected value and edge.', tool: 'ev', sections: [
    ['Find a positive expected value price', 'Enter the stake, American odds, and your estimated probability of winning. The tool calculates expected net profit, return on stake, break-even probability, and the difference between your estimate and the price’s break-even rate.', 'A positive result depends on the probability you supply. The calculator does not identify opportunities from live odds or generate picks.'],
    ['Positive EV is a long-run measure', 'A positive expected value wager is priced above break-even under a probability estimate. It can still lose, and short-term results do not prove that the estimate was accurate. The edge becomes more meaningful when estimates are calibrated and prices are recorded before the event.', 'For instance, a 50% estimate at +110 yields $5 EV per $100 stake. A 45% estimate at the same price yields negative EV, even though the payout looks attractive.'],
    ['Make the estimate transparent', 'Record how you arrived at the probability and compare it with no-vig market prices. Check the market definition, line movement, and odds at placement. Recalculate if a price changes; a wager can move from positive to negative EV as the odds shift.']
  ], faqs: [['What is a positive EV bet?', 'It is a wager whose expected net return is above zero under the probability estimate and payout entered.'], ['How do I find +EV bets?', 'Compare a credible probability estimate with the price’s break-even probability and confirm the offered odds. This calculator evaluates an entered price; it does not scan markets.'], ['Can positive EV betting guarantee profit?', 'No. A positive estimate can lose and depends on probability accuracy, execution, and repeatable pricing.']] }
];

const education = {
  slug: 'positive-ev', title: 'Positive Expected Value Betting: A Practical Guide', short: 'Learn what +EV means, how to calculate expected value, and how to evaluate a price.', tool: 'ev', sections: [
    ['What positive expected value means', 'Positive expected value, often written +EV, means the estimated average net return of a wager is above zero at the odds offered. It compares a probability estimate with the sportsbook’s payout. A positive EV bet may lose; the number describes the average result across many comparable wagers if the assumptions hold.', 'For a $100 bet at +110, a win earns $110 profit and a loss costs $100. If the estimated chance of winning is 50%, expected value is 0.50 × $110 − 0.50 × $100 = $5. The expected return is 5% of the stake.'],
    ['How to calculate expected value', 'Convert the offered American odds into net profit on a win. Multiply that profit by the estimated win probability. Subtract the stake multiplied by the probability of losing. If the result is positive, the bet is positive EV under that estimate. The break-even probability is the stake divided by the total amount returned on a win.', 'At -110, the break-even rate is about 52.38%. An estimate above that threshold implies positive EV before fees and other settlement effects; an estimate below it implies negative EV.'],
    ['Where should probability estimates come from?', 'An estimate can come from a validated model, a no-vig market consensus, or a transparent handicapping process. Each source has limitations. Market prices include information from other bettors but can differ by book and market. A model can be wrong because of missing data, calibration error, or a poor fit to the event.', 'Record the estimate and its source before placing the wager. Compare your probabilities with closing prices and long-run results across a meaningful sample. One win or loss does not validate a model.'],
    ['Positive EV betting is not a guarantee', 'Expected value is a repeated-trial concept. Variance can dominate a short sample, especially when wagers have long odds. Stake sizing, price shopping, and probability calibration affect the result, and none removes the chance of losing. The EV calculator on this page makes the assumptions visible; it does not supply predictions or live opportunities.'],
    ['Use a careful workflow', 'Check that your probability and sportsbook line describe the same selection and settlement rules. Remove market margin when using odds as a fair-price reference. Recalculate after line movement, keep a record of accepted odds, and treat staking outputs as estimates rather than instructions.']
  ], faqs: [['What does +EV mean in sports betting?', 'It means the expected net return is positive at the odds offered under a stated win-probability estimate. It does not mean the next bet is expected to win.'], ['How do I calculate EV for a bet?', 'Multiply win probability by net profit on a win, then subtract loss probability multiplied by stake. Convert odds to payout first.'], ['Is +EV the same as a guaranteed win?', 'No. Positive expected value wagers can lose. The term describes a long-run average under assumptions, not a guaranteed outcome.'], ['What is a good EV percentage?', 'There is no universal target. A larger estimated edge can also reflect a less accurate probability estimate. Evaluate calibration, market quality, and sample size.']] }
;

const calcIndex = calculators.map(item => ({ ...item, href: `${CALCULATOR_BASE}/${item.slug}` }));
const toolIndex = tools.map(item => ({ ...item, href: `${TOOLS_BASE}/${item.slug}` }));
const calcBySlug = new Map(calculators.map(item => [item.slug, item]));
const toolBySlug = new Map(tools.map(item => [item.slug, item]));
const esc = value => String(value).replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[ch]);
const jsonLd = value => JSON.stringify(value).replace(/</g, '\\u003c');

function input(name, label, value, hint = '', { step = 'any', min = '', max = '', unit = '' } = {}) {
  return `<label class="bet-input"><span>${label}</span><span class="bet-control">${unit ? `<i>${unit}</i>` : ''}<input name="${name}" type="number" inputmode="decimal" step="${step}"${min !== '' ? ` min="${min}"` : ''}${max !== '' ? ` max="${max}"` : ''} value="${value}" required aria-label="${label}"></span>${hint ? `<small>${hint}</small>` : ''}</label>`;
}
function select(name, label, choices, hint = '') {
  return `<label class="bet-input"><span>${label}</span><select name="${name}">${choices.map(([value, text]) => `<option value="${value}">${text}</option>`).join('')}</select>${hint ? `<small>${hint}</small>` : ''}</label>`;
}
function fieldset(title, fields) { return `<fieldset class="bet-fields"><legend>${title}</legend><div class="bet-field-grid">${fields}</div></fieldset>`; }

function formFor(kind) {
  switch (kind) {
    case 'arbitrage': return fieldset('Market prices', input('oddsA', 'Outcome A American odds', 120, 'Example: +120 is entered as 120.') + input('oddsB', 'Outcome B American odds', 110, 'Use the opposing side price.')) + fieldset('Stake plan', input('bankroll', 'Total bankroll to allocate', 100, '', { min: 0.01, unit: '$' }));
    case 'ev': return fieldset('Your bet', input('stake', 'Stake', 100, '', { min: 0.01, unit: '$' }) + input('odds', 'American odds', 110, 'Positive or negative price.') + input('probability', 'Estimated win probability', 50, 'Your estimate, from 0% to 100%.', { min: 0, max: 100, unit: '%' }));
    case 'freebet': return fieldset('Bonus bet and hedge', input('token', 'Free bet token value', 100, 'Assumes the stake is not returned.', { min: 0.01, unit: '$' }) + input('oddsA', 'Free bet side American odds', 200) + input('oddsB', 'Opposing cash bet American odds', -200, 'Enter the price on the other outcome.'));
    case 'halfpoint': return fieldset('Current and alternate line', input('stake', 'Stake', 100, '', { min: 0.01, unit: '$' }) + input('oldOdds', 'Current line American odds', -110) + input('newOdds', 'Half-point line American odds', -125) + input('cover', 'Current line cover probability', 50, '', { min: 0, max: 100, unit: '%' }) + input('added', 'Probability added by half point', 2, 'Estimate for this sport and market.', { min: 0, max: 100, unit: '%' }));
    case 'hold': case 'novig': case 'vig': return fieldset('Two-way market prices', input('oddsA', 'Outcome A American odds', -110) + input('oddsB', 'Outcome B American odds', -110, 'Enter the opposite outcome price.'));
    case 'implied': case 'odds': return fieldset('Price to convert', input('odds', 'American odds', -110, 'Positive and negative prices are supported.'));
    case 'kelly': return fieldset('Bankroll and edge', input('bankroll', 'Bankroll', 1000, '', { min: 0.01, unit: '$' }) + input('odds', 'American odds', 110) + input('probability', 'Estimated win probability', 52, '', { min: 0, max: 100, unit: '%' }) + input('fraction', 'Kelly fraction', 25, 'For example, 25 means quarter Kelly.', { min: 0, max: 100, unit: '%' }));
    case 'parlay': case 'parlaybuilder': return fieldset('Parlay legs', `<div class="parlay-leg"><label class="bet-check"><input type="checkbox" name="include1" checked>Leg 1</label>${input('odds1', 'Leg 1 American odds', -110)}${input('prob1', 'Leg 1 win probability', 55, '', { min: 0, max: 100, unit: '%' })}</div><div class="parlay-leg"><label class="bet-check"><input type="checkbox" name="include2" checked>Leg 2</label>${input('odds2', 'Leg 2 American odds', 120)}${input('prob2', 'Leg 2 win probability', 52, '', { min: 0, max: 100, unit: '%' })}</div><div class="parlay-leg"><label class="bet-check"><input type="checkbox" name="include3" checked>Leg 3</label>${input('odds3', 'Leg 3 American odds', 105)}${input('prob3', 'Leg 3 win probability', 53, '', { min: 0, max: 100, unit: '%' })}</div><div class="parlay-leg"><label class="bet-check"><input type="checkbox" name="include4">Leg 4</label>${input('odds4', 'Leg 4 American odds', -105)}${input('prob4', 'Leg 4 win probability', 51, '', { min: 0, max: 100, unit: '%' })}</div>`) + fieldset('Parlay stake', input('stake', 'Stake', 20, '', { min: 0.01, unit: '$' }));
    case 'spread': return fieldset('Final score and spread', input('teamScore', 'Selected team score', 24, '', { min: 0, step: 1 }) + input('opponentScore', 'Opponent score', 20, '', { min: 0, step: 1 }) + input('spread', 'Selected team spread', -3.5, 'Favorite is negative; underdog is positive.') + input('odds', 'American odds', -110) + input('stake', 'Stake', 100, '', { min: 0.01, unit: '$' }));
    case 'poisson': return fieldset('Event count model', input('mean', 'Expected average (lambda)', 2, '', { min: 0, max: 100 }) + input('threshold', 'Event count', 2, 'Use a whole number.', { min: 0, max: 100, step: 1 }) + select('mode', 'Probability to calculate', [['exact', 'Exactly this many'], ['atleast', 'At least this many'], ['atmost', 'At most this many']]));
    case 'roundrobin': return fieldset('Selections and combination size', input('odds1', 'Selection 1 American odds', 110) + input('odds2', 'Selection 2 American odds', -110) + input('odds3', 'Selection 3 American odds', 125) + input('odds4', 'Selection 4 American odds', 105) + select('legs', 'Parlay size', [['2', '2 selections per parlay'], ['3', '3 selections per parlay']]) + input('unitStake', 'Stake per combination', 5, '', { min: 0.01, unit: '$' }));
    case 'lowhold': return fieldset('Prices at two sportsbooks', input('a1', 'Book 1 · Outcome A', -110) + input('b1', 'Book 1 · Outcome B', -110) + input('a2', 'Book 2 · Outcome A', 100) + input('b2', 'Book 2 · Outcome B', -120, 'The tool selects the best price for each outcome.'));
    case 'middle': return fieldset('Opposing lines and prices', input('overLine', 'Over line', 47.5) + input('underLine', 'Under line', 51.5) + input('overOdds', 'Over American odds', -110) + input('underOdds', 'Under American odds', -110) + input('overStake', 'Over stake', 100, '', { min: 0.01, unit: '$' }) + input('underStake', 'Under stake', 100, '', { min: 0.01, unit: '$' }));
    case 'boosts': return fieldset('Compare the promotion price', input('stake', 'Eligible stake', 20, '', { min: 0.01, unit: '$' }) + input('original', 'Original American odds', 100) + input('boosted', 'Boosted American odds', 150) + input('probability', 'Estimated win probability', 48, '', { min: 0, max: 100, unit: '%' }));
    default: return '';
  }
}

function paragraph(text) { return `<p>${esc(text)}</p>`; }
function renderFaqs(faqs, title = 'Frequently asked questions') {
  return `<section class="bet-faq" aria-label="${esc(title)}"><h2>${esc(title)}</h2>${faqs.map(([q, a]) => `<details><summary>${esc(q)}</summary>${paragraph(a)}</details>`).join('')}</section>`;
}
function renderArticle(sections, faqs) {
  return `<article class="bet-article" aria-label="Betting guide">${sections.map(([title, ...body]) => `<section><h2>${esc(title)}</h2>${body.map(paragraph).join('')}</section>`).join('')}${renderFaqs(faqs)}</article>`;
}
function schemaFaq(faqs) { return { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }; }
function toolPanel(item) {
  return `<section class="bet-tool" aria-labelledby="tool-title"><div class="bet-tool-heading"><div><p class="bet-tool-kicker">Interactive calculator</p><h2 id="tool-title">${esc(item.title)}</h2><p>${esc(item.short)}</p></div><span class="bet-live-indicator"><i></i> Manual market inputs</span></div><form id="bet-form" data-tool="${esc(item.tool)}">${formFor(item.tool)}<div class="bet-form-actions"><button class="bet-submit" type="submit">Calculate result</button><button class="bet-reset" type="reset">Reset example</button></div></form><section class="bet-result" aria-live="polite" aria-atomic="true"><div class="bet-result-top"><span>Calculation</span><span id="bet-result-status">Example inputs</span></div><h3 id="bet-result-title">Adjust the example values</h3><p id="bet-result-note">Results update from the prices and assumptions you enter.</p><dl id="bet-result-values"></dl></section><p class="bet-tool-note">Manual calculator · no live sportsbook prices. Verify the odds, promotion terms, and market rules before placing a wager.</p></section>`;
}

function itemCards(items, base) {
  return `<div class="bet-link-grid">${items.map(item => `<a class="bet-link-card" href="${base}/${esc(item.slug)}"><span class="bet-card-category">${item.tool === 'poisson' ? 'Probability' : item.tool === 'arbitrage' ? 'Price comparison' : item.tool === 'kelly' ? 'Bankroll' : 'Betting calculator'}</span><h3>${esc(item.title)}</h3><p>${esc(item.short)}</p><span class="bet-card-link">Open calculator</span></a>`).join('')}</div>`;
}
function hubContent(type) {
  if (type === 'calculators') return `<section class="bet-hub-intro"><h2>Free sports betting calculators</h2><p>Convert odds, estimate expected value, compare market prices, and plan common wagers with these free sports betting calculators. Each calculator runs from the prices and assumptions you enter.</p><label class="bet-search-label" for="bet-search">Find a calculator</label><input id="bet-search" type="search" placeholder="Search odds, EV, parlay…" autocomplete="off"><p id="bet-search-count" aria-live="polite">${calculators.length} calculators</p><p id="bet-search-empty" hidden>No calculators match that search. Try a different term.</p></section><section class="bet-hub-group"><h2>Odds and probability</h2>${itemCards(calculators.filter(x => ['odds-converter', 'implied-probability', 'no-vig-fair-odds', 'hold', 'vig', 'poisson'].includes(x.slug)), CALCULATOR_BASE)}</section><section class="bet-hub-group"><h2>Wager planning</h2>${itemCards(calculators.filter(x => ['expected-value', 'kelly-criterion', 'parlay', 'round-robin', 'point-spread', 'half-point'].includes(x.slug)), CALCULATOR_BASE)}</section><section class="bet-hub-group"><h2>Arbitrage and promotions</h2>${itemCards(calculators.filter(x => ['arbitrage-hedge-bet', 'free-bet-conversion'].includes(x.slug)), CALCULATOR_BASE)}</section><section class="bet-hub-guide"><h2>How to use a sports betting calculator</h2><p>Start with the exact price on your bet slip. American odds such as -110 and +150 convert to implied probabilities and decimal payouts. For expected value, add your own win-probability estimate; for no-vig odds, enter every outcome in the market. The calculators show the arithmetic from those inputs and do not fetch live sportsbook lines.</p><p>Use the relevant guide to understand each formula, its assumptions, and what the result can tell you. Prices can move, and settlement terms can differ between books.</p><a href="/betting-education/positive-ev">Read the positive expected value betting guide</a></section>${renderFaqs(hubFaqs.calculators)}`;
  return `<section class="bet-hub-intro"><h2>Sports betting tools and planners</h2><p>Use these manual betting tools to compare odds you have found, evaluate promotions, plan a hedge, or build a parlay from your own estimates. Every result is based on user-entered prices; live odds and sportsbook opportunity feeds are not connected.</p><label class="bet-search-label" for="bet-search">Find a betting tool</label><input id="bet-search" type="search" placeholder="Search arbitrage, middle, boost…" autocomplete="off"><p id="bet-search-count" aria-live="polite">${tools.length} tools</p><p id="bet-search-empty" hidden>No tools match that search. Try a different term.</p></section><section class="bet-hub-group"><h2>Compare sportsbook prices</h2>${itemCards(tools.filter(x => ['arbitrage', 'low-hold', 'middles'].includes(x.slug)), TOOLS_BASE)}</section><section class="bet-hub-group"><h2>Promotions and bonuses</h2>${itemCards(tools.filter(x => ['boosts', 'free-bet-converter'].includes(x.slug)), TOOLS_BASE)}</section><section class="bet-hub-group"><h2>Bet planning</h2>${itemCards(tools.filter(x => ['parlay-builder', 'positive-ev'].includes(x.slug)), TOOLS_BASE)}</section><section class="bet-hub-guide"><h2>Use the tools with current, matching prices</h2><p>Check that both sides refer to the same game, market period, and settlement rules before calculating. A mathematical estimate can change when the price moves or a sportsbook limits the accepted stake. These pages help with the calculation; they do not place bets or provide picks.</p><a href="/betting-calculators">Browse all sports betting calculators</a></section>${renderFaqs(hubFaqs.tools)}`;
}

const hubFaqs = {
  calculators: [
    ['What can a sports betting calculator calculate?', 'These calculators convert odds, estimate implied and no-vig probabilities, evaluate expected value, size selected stakes, and estimate payouts from user-entered numbers.'],
    ['Do these betting calculators use live sportsbook odds?', 'No. Enter the current price from your sportsbook. The calculators perform the math locally and do not scan or refresh odds feeds.'],
    ['How do American odds convert to implied probability?', 'For positive odds, divide 100 by the odds plus 100. For negative odds, divide the absolute odds by that number plus 100.']
  ],
  tools: [
    ['Do the sports betting tools show live opportunities?', 'No. These manual tools calculate from the odds, stakes, and assumptions you enter. They do not scan sportsbook markets.'],
    ['Can an arbitrage tool guarantee a profit?', 'The calculation can show a positive balanced return at entered prices, but accepted stakes, price changes, and matching settlement rules are necessary for that result.'],
    ['Do these betting tools place a wager?', 'No. They help compare prices and estimate outcomes. Review the sportsbook ticket and terms directly before placing any wager.']
  ]
};

function related(item, type) {
  const entries = type === 'calculator' ? calcIndex : type === 'tool' ? toolIndex : [];
  const requested = item.slug.includes('free-bet') ? ['free-bet-conversion', 'odds-converter', 'expected-value'] : item.slug.includes('parlay') ? ['parlay', 'expected-value', 'kelly-criterion'] : item.slug.includes('arbitrage') ? ['arbitrage-hedge-bet', 'hold', 'no-vig-fair-odds'] : item.slug.includes('ev') ? ['expected-value', 'no-vig-fair-odds', 'kelly-criterion'] : ['odds-converter', 'implied-probability', 'expected-value'];
  const links = requested.map(slug => calcIndex.find(x => x.slug === slug)).filter(Boolean).filter(x => x.slug !== item.slug).slice(0, 3);
  return `<nav class="bet-related" aria-label="Related betting guides"><h2>Related calculators</h2>${links.map(link => `<a href="${link.href}">${esc(link.title)}</a>`).join('')}</nav>`;
}

export const bettingPagePaths = [
  CALCULATOR_BASE, ...calculators.map(item => `${CALCULATOR_BASE}/${item.slug}`),
  TOOLS_BASE, ...tools.map(item => `${TOOLS_BASE}/${item.slug}`),
  '/betting-education/positive-ev'
];

export function renderBettingPage(url, origin = '') {
  const pathname = url.pathname.replace(/\/$/, '') || '/';
  let page, kind;
  if (pathname === CALCULATOR_BASE) { page = { title: 'Free Sports Betting Calculators', short: 'Odds, expected value, vig, parlay, and bankroll calculators for sports bettors.' }; kind = 'calculators'; }
  else if (pathname === TOOLS_BASE) { page = { title: 'Sports Betting Tools', short: 'Practical tools for arbitrage, low-hold markets, odds boosts, middle bets, and parlays.' }; kind = 'tools'; }
  else if (pathname === '/betting-education/positive-ev') { page = education; kind = 'education'; }
  else if (pathname.startsWith(`${CALCULATOR_BASE}/`)) { page = calcBySlug.get(pathname.slice(CALCULATOR_BASE.length + 1)); kind = 'calculator'; }
  else if (pathname.startsWith(`${TOOLS_BASE}/`)) { page = toolBySlug.get(pathname.slice(TOOLS_BASE.length + 1)); kind = 'tool'; }
  else return null;
  if (!page) return null;
  const fullTitle = `${page.title} | Sports Lab`;
  const canonical = `${origin}${pathname}`;
  const isHub = kind === 'calculators' || kind === 'tools';
  const description = kind === 'calculators' ? 'Free sports betting calculators for odds conversion, expected value, implied probability, vig, parlays, and bankroll decisions.'
    : kind === 'tools' ? 'Use manual sports betting tools to size arbitrage stakes, convert bonus bets, check a middle, and compare low-hold prices.'
      : kind === 'education' ? 'Learn positive expected value betting with a worked example, the EV formula, break-even odds, and a practical guide to probability estimates.'
        : `${page.short} Includes the formula, examples, assumptions, and answers to common questions.`;
  const faqSchema = `<script type="application/ld+json">${jsonLd(schemaFaq(isHub ? hubFaqs[kind] : page.faqs))}</script>`;
  const schema = { '@context': 'https://schema.org', '@type': isHub ? 'CollectionPage' : kind === 'education' ? 'Article' : 'WebApplication', name: page.title, description, url: canonical, ...(isHub ? { mainEntity: { '@type': 'ItemList', itemListElement: (kind === 'calculators' ? calcIndex : toolIndex).map((item, index) => ({ '@type': 'ListItem', position: index + 1, url: `${origin}${item.href}`, name: item.title })) } } : kind === 'education' ? { headline: page.title, mainEntityOfPage: canonical, articleSection: 'Sports betting education', about: ['positive expected value betting', 'sports betting expected value', 'sports betting odds'] } : { applicationCategory: 'FinanceApplication', operatingSystem: 'Web', isAccessibleForFree: true }) };
  const pageSchema = `<script type="application/ld+json">${jsonLd(schema)}</script>`;
  const body = isHub ? hubContent(kind) : `${toolPanel(page)}${renderArticle(page.sections, page.faqs)}${related(page, kind)}`;
  const breadcrumbs = isHub ? [{ label: 'Sports Lab', href: '/' }, { label: page.title }] : [{ label: 'Sports Lab', href: '/' }, { label: kind === 'education' ? 'Betting education' : kind === 'tool' ? 'Betting tools' : 'Betting calculators', href: kind === 'education' ? '/betting-education' : kind === 'tool' ? TOOLS_BASE : CALCULATOR_BASE }, { label: page.title }];
  const crumbHtml = `<nav class="bet-breadcrumbs" aria-label="Breadcrumb">${breadcrumbs.map((crumb, index) => index === breadcrumbs.length - 1 ? `<span aria-current="page">${esc(crumb.label)}</span>` : `<a href="${crumb.href}">${esc(crumb.label)}</a>`).join('<span aria-hidden="true">/</span>')}</nav>`;
  const breadcrumbSchema = `<script type="application/ld+json">${jsonLd({ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: breadcrumbs.map((crumb, index) => ({ '@type': 'ListItem', position: index + 1, name: crumb.label, item: `${origin}${crumb.href || pathname}` })) })}</script>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#080d12"><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="${kind === 'education' ? 'article' : 'website'}"><meta property="og:site_name" content="Sportslab"><meta property="og:title" content="${esc(fullTitle)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta name="twitter:card" content="summary"><link rel="preload" href="/assets/fonts/InterVariable.woff2" as="font" type="font/woff2" crossorigin><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/betting-pages.css"><title>${esc(fullTitle)}</title>${pageSchema}${breadcrumbSchema}${faqSchema}</head><body class="betting-pages"><a class="bet-skip" href="#main">Skip to page content</a><header class="bet-header"><a class="bet-brand" href="/" aria-label="Sports Lab home"><img src="/favicon.svg" width="34" height="34" alt=""><span>sports<span>lab</span></span></a><nav aria-label="Betting resources"><a${kind === 'calculators' || kind === 'calculator' || kind === 'education' ? ' aria-current="page"' : ''} href="${CALCULATOR_BASE}">Calculators</a><a${kind === 'tools' || kind === 'tool' ? ' aria-current="page"' : ''} href="${TOOLS_BASE}">Tools</a><a href="/betting-education/positive-ev">Betting guides</a></nav><a class="bet-header-back" href="/nfl">NFL research</a></header><main id="main" class="bet-main">${crumbHtml}<header class="bet-page-heading"><h1>${esc(page.title)}</h1><p>${esc(page.short)}</p></header>${body}<footer class="bet-footer"><a href="/">Sports Lab</a><span>Independent sports research and manual betting calculators.</span><a href="/betting-calculators">All calculators</a><a href="/betting-tools">All tools</a></footer></main><script type="module" src="/betting-pages.js"></script></body></html>`;
}

export function renderBettingSitemapEntries(origin) {
  const stamp = '2026-09-24';
  return bettingPagePaths.filter(loc => loc !== '/betting-education/positive-ev').map(loc => `<url><loc>${esc(origin + loc)}</loc><lastmod>${stamp}</lastmod><changefreq>monthly</changefreq></url>`).join('');
}
