const weekly='nflverse weekly player stats',pbp='nflverse play-by-play';
export const definitions={
 receiving_ypg:`${weekly}: receiving yards ÷ sample appearances.`,
 yards_per_target:`${weekly}: receiving yards ÷ targets in the same sample.`,
 pass_attempt_share:`${weekly}: player passing attempts ÷ team passing attempts in the same sample games.`,
 completions_pg:`${weekly}: passing completions ÷ sample appearances.`,
 completion_pct:`${weekly}: completions ÷ passing attempts.`,
 interceptions_pg:`${weekly}: passing interceptions thrown ÷ sample appearances.`,
 interception_pct:`${weekly}: interceptions thrown ÷ passing attempts.`,
 rush_rec_ypg:`${weekly}: (rushing yards + receiving yards) ÷ sample appearances. Passing yards are excluded.`,
 opp_carries_allowed_pg:'Opponent last eight completed regular-season games: all opposing player carries ÷ games. Includes official kneel-down attempts.',
 opp_receiving_ypg_allowed:'Opponent last eight completed regular-season games: receiving yards allowed to this player’s position ÷ games.',
 opp_pass_attempts_allowed_pg:'Opponent last eight completed regular-season games: all opposing passing attempts ÷ games.',
 opp_completions_allowed_pg:'Opponent last eight completed regular-season games: completions by opposing passers ÷ games.',
 opp_interceptions_pg:'Opponent last eight completed regular-season games: interceptions thrown by opposing passers ÷ games.',
 opp_rush_rec_ypg_allowed:'Opponent last eight completed regular-season games: rushing + receiving yards allowed to this player’s position ÷ games.',
 touches_pg:`${weekly}: (carries + targets) ÷ meaningful sampled games. Includes official kneel-down carries.`,
 rz_touch_share:`${pbp}: player's carries + targets inside the opponent 20 ÷ team carries + targets there in the same games. Excludes kneels, spikes, nullified plays and two-point tries.`,
 goal_line_carries_pg:`${pbp}: carries starting within 5 yards of the goal line ÷ sampled games; kneels excluded.`,
 target_share_avg:`${weekly}: player targets ÷ team targets across the same sample.`,
 target_share:`${weekly}: player targets ÷ team targets across the same sample.`,
 td_per_touch:`${weekly}: (rushing TDs + receiving TDs) ÷ (carries + targets). Passing TDs are not player scoring TDs.`,
 games_since_td:'Consecutive sample appearances without a rushing or receiving touchdown, capped at the five-game sample.',
 snap_pct_avg:'Pro Football Reference snap counts via nflverse: average offensive snap percentage over available sample games. Missing snap games are omitted, not counted as zero.',
 implied_total:'nflverse schedule: (game total + points favored) ÷ 2. Missing lines remain blank. Historical lines may be closing lines.',
 points_favored:'nflverse schedule spread_line: positive means this team is favored. The home spread is positive for home favorites; negate for the away team.',
 opp_td_allowed_pg:'Opponent last eight completed regular-season games: rushing + receiving TDs allowed to this player’s position ÷ opponent games.',
 attempts_pg:`${weekly}: pass attempts ÷ sample games. Sacks excluded; official spikes included.`,
 pass_ypg:`${weekly}: passing yards ÷ sample games.`,
 ypa:`${weekly}: passing yards ÷ attempts.`,
 adot:`${pbp}: mean air_yards on this player's pass attempts with a recorded depth.`,
 air_volume:`${pbp}: summed recorded air_yards ÷ sample games.`,
 sack_rate:`${weekly}: sacks suffered ÷ (attempts + sacks suffered).`,
 opp_pass_ypg_allowed:'Opponent last eight completed regular-season games: total player passing yards allowed ÷ games.',
 opp_sack_rate_forced:'Opponent last eight completed regular-season games: sacks suffered by opposing passers ÷ their attempts plus sacks.',
 yardage_debt:'Local model: sum prior-season league passing yards per non-spike attempt in each depth bin over sampled non-spike attempts, minus actual passing yards. Bins: behind line, 0–9, 10–19, 20+, unknown. Not an NFL NGS metric.',
 rz_pass_rate:`${pbp}: current team's last five completed regular-season games, pass attempts inside the opponent 10 ÷ team passes plus modeled carries there; excludes sacks and kneels.`,
 rz_attempts_pg:`${pbp}: this player's pass attempts starting inside the opponent 10 ÷ sampled games.`,
 pass_tds_pg:`${weekly}: passing touchdowns ÷ sample games.`,
 end_zone_acc:`${pbp}: completions ÷ attempts where air_yards reaches the starting yardline_100. Unknown depths are omitted.`,
 opp_pass_tds_allowed_pg:'Opponent last eight completed regular-season games: passing TDs allowed ÷ games.',
 passtd_debt:'Local model: prior-season league TD rates per non-spike pass attempt (including throwaways, excluding sacks) by starting field zone, applied to the same type of sampled attempts, minus actual passing TDs.',
 carry_share:`${weekly}: player carries ÷ team carries over the same sample; includes official kneels.`,
 carries_pg:`${weekly}: carries ÷ sample games.`,
 rush_ypg:`${weekly}: rushing yards ÷ sample games.`,
 ypc:`${weekly}: rushing yards ÷ carries.`,
 explosive_pct:`${pbp}: modeled carries gaining at least 10 yards ÷ modeled carries (kneels excluded).`,
 stuff_avoid_pct:`${pbp}: modeled carries gaining more than zero yards ÷ modeled carries (kneels excluded).`,
 opp_light_box_rate:'FTN via nflverse: opponent defended carries with 1–6 box defenders ÷ defended carries with recorded box count in the opponent sample. Only charted carries count; usually prior-season games during the current season. See charted-carry count. Zero/unknown defenders are excluded.',
 opp_charted_carries:'Number of non-kneel opponent-sample carries with recorded positive box counts used by the light-box rate. Current-season free participation charting is unavailable until the postseason ends.',
 opp_ypc_allowed:'Opponent last eight completed regular-season games: opponent rushing yards ÷ carries, including official kneels.',
 rush_debt:'NFL Next Gen Stats via nflverse: negative of summed rush_yards_over_expected across matched published sample games. Positive means fewer yards than the NFL tracking model expected. Uses the published RYOE field, since its tracked attempts may differ from all rush_yards. Missing games are excluded; see NGS game count.',
 rush_baseline_gap:'Local model: prior-season league mean rushing yards by field zone applied to sampled non-kneel carries, minus yards on those carries. Separate from NFL NGS.',
 ngs_rush_over_expected:'NFL Next Gen Stats: sum rush_yards_over_expected across matched published sample games. Positive means more yards than the tracking model expected.',
 ngs_rush_games:'Number of sample games with published NGS rushing expectations. Zero means no published data; no estimate is substituted.',
 ngs_time_to_throw:'NFL Next Gen Stats: average time to throw in seconds, weighted by attempts across matched published sample weeks.',
 ngs_separation:'NFL Next Gen Stats: average separation in yards, weighted by targets across matched published sample weeks.',
 targets_pg:`${weekly}: targets ÷ sample games.`,
 rec_pg:`${weekly}: receptions ÷ sample games.`,
 catch_pct:`${weekly}: receptions ÷ targets.`,
 quick_share:`${pbp}: this player's targets with air_yards ≤5 ÷ team targets with air_yards ≤5 in the same meaningful games. This measures quick-game role, not time to throw.`,
 opp_rec_allowed_pg:'Opponent last eight completed regular-season games: all receptions allowed ÷ games.',
 opp_catch_rate_allowed:'Opponent last eight completed regular-season games: all receptions ÷ all targets allowed.',
 reception_debt:'Local model: prior-season league completions per assigned target by target-depth bin applied to sampled targets, minus receptions. Positive does not guarantee future regression.',
};
