export const SOCCER_LEAGUES={'eng.1':'Premier League','esp.1':'La Liga','ger.1':'Bundesliga','ita.1':'Serie A','fra.1':'Ligue 1','usa.1':'MLS','uefa.champions':'Champions League'};
const m=(label,fields,line,extra={})=>({label,fields:fields.split(','),benchmark:line,...extra});
export const isBasketball=sport=>sport==='nba'||sport==='wnba';
export const SPORTS={
 wnba:{label:'WNBA',title:'WNBA Lab',path:'basketball/wnba',duration:40,maximumMinutes:40,minimum:5,markets:{points:m('Points','points',15.5),rebounds:m('Rebounds','rebounds',5.5),assists:m('Assists','assists',3.5),threes:m('Three-pointers','threePointFieldGoalsMade',1.5),pra:m('Points + rebounds + assists','points,rebounds,assists',24.5),pr:m('Points + rebounds','points,rebounds',20.5),pa:m('Points + assists','points,assists',19.5),ra:m('Rebounds + assists','rebounds,assists',8.5),steals:m('Steals','steals',.5),blocks:m('Blocks','blocks',.5),stocks:m('Steals + blocks','steals,blocks',1.5),turnovers:m('Turnovers','turnovers',2.5),fgm:m('Field goals made','fieldGoalsMade',5.5),fga:m('Field goal attempts','fieldGoalsAttempted',12.5),ftm:m('Free throws made','freeThrowsMade',2.5)}},
 nba:{label:'NBA',title:'Court Lab',path:'basketball/nba',duration:48,minimum:5,markets:{points:m('Points','points',19.5),rebounds:m('Rebounds','rebounds',5.5),assists:m('Assists','assists',4.5),threes:m('Three-pointers','threePointFieldGoalsMade',2.5),pra:m('Points + rebounds + assists','points,rebounds,assists',29.5),pr:m('Points + rebounds','points,rebounds',24.5),pa:m('Points + assists','points,assists',24.5),ra:m('Rebounds + assists','rebounds,assists',9.5),steals:m('Steals','steals',.5),blocks:m('Blocks','blocks',.5),turnovers:m('Turnovers','turnovers',2.5)}},
 nhl:{label:'NHL',title:'Ice Lab',path:'hockey/nhl',duration:60,minimum:5,markets:{shots:m('Shots on goal','shotsTotal',2.5),goals:m('Goals','goals',.5),assists:m('Assists','assists',.5),points:m('Points','goals,assists',.5),blocks:m('Blocked shots','blockedShots',1.5),hits:m('Hits','hits',1.5),saves:m('Goalie saves','saves',24.5,{goalie:true})}},
 soccer:{label:'Soccer',title:'Pitch Lab',path:'soccer/eng.1',duration:90,minimum:5,markets:{shots:m('Shots','totalShots',1.5),sot:m('Shots on target','shotsOnTarget',.5),goals:m('Goals','totalGoals',.5),assists:m('Assists','goalAssists',.5),fouls:m('Fouls committed','foulsCommitted',1.5),cards:m('Yellow cards','yellowCards',.5),saves:m('Goalkeeper saves','saves',2.5,{goalie:true}),team_goals:m('Team goals','totalGoals',1.5,{team:true}),corners:m('Team corners','wonCorners',4.5,{team:true})}}
};
export const day=(now=Date.now())=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now));
export function query(input={},now=Date.now()){
 const sport=input.sport,date=input.date||day(now),config=SPORTS[sport],league=sport==='soccer'?(input.league||'eng.1'):sport;
 const market=input.market||Object.keys(config?.markets||{})[0],gameId=input.game||null;
 if(!config||!config.markets[market]||sport==='soccer'&&!SOCCER_LEAGUES[league]||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date+'T12:00Z').toISOString().slice(0,10)!==date||date<'2005-01-01'||date>'2100-12-31'||gameId&&!/^\d{6,12}$/.test(gameId))throw Object.assign(Error('Choose a valid sport, league, date, matchup and prop.'),{status:400});
 return {sport,date,league,market,gameId,path:sport==='soccer'?'soccer/'+league:config.path};
}
